+ check for run by Xcode in scripts

diff --git a/misc/scripts/deploy_image b/misc/scripts/deploy_image
--- a/misc/scripts/deploy_image
+++ b/misc/scripts/deploy_image
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+if [ -z "${SRCROOT}" ]; then
+	echo "Error: this script must be run by Xcode"
+	exit 1
+fi
+
 if [ "$1" != "Cocoa" ] && [ "$1" != "SDL" ]; then
 	echo "Usage: deploy_image [Cocoa|SDL]"
 	exit 1
diff --git a/misc/scripts/post_build b/misc/scripts/post_build
--- a/misc/scripts/post_build
+++ b/misc/scripts/post_build
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+if [ -z "${SRCROOT}" ]; then
+	echo "Error: this script must be run by Xcode"
+	exit 1
+fi
+
 GZDOOM_EXEC_DIR=${CONFIGURATION_BUILD_DIR}/${EXECUTABLE_FOLDER_PATH}
 
 if [ ! -e "${GZDOOM_EXEC_DIR}" ]; then
diff --git a/misc/scripts/sc_man_scanner b/misc/scripts/sc_man_scanner
--- a/misc/scripts/sc_man_scanner
+++ b/misc/scripts/sc_man_scanner
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+if [ -z "${SRCROOT}" ]; then
+	echo "Error: this script must be run by Xcode"
+	exit 1
+fi
+
 echo "Generating sc_man_scanner.h..."
 
 cd "${SRCROOT}/src"
diff --git a/misc/scripts/xlat_parser b/misc/scripts/xlat_parser
--- a/misc/scripts/xlat_parser
+++ b/misc/scripts/xlat_parser
@@ -1,8 +1,13 @@
 #!/bin/sh
 
+if [ -z "${SRCROOT}" ]; then
+	echo "Error: this script must be run by Xcode"
+	exit 1
+fi
+
 echo "Generating xlat_parser.c and xlat_parser.h..."
 
 cp -f "${SRCROOT}/tools/lemon/lempar.c" "${CONFIGURATION_BUILD_DIR}/lempar.c"
-	
+
 cd "${SRCROOT}/src/xlat"
 "${CONFIGURATION_BUILD_DIR}/lemon" xlat_parser.y
